FROM golang:1.18.2 as build

WORKDIR /go/src/app
COPY . .

RUN go mod init go-github-fetcher
RUN go get -d ./...
RUN go vet -v
RUN go test ./... -v configpkg=./... 

RUN CGO_ENABLED=0 go build -o /go/bin/app

FROM gcr.io/distroless/static

COPY --from=build /go/bin/app /
CMD ["/app"]