version: '3.3'

services:
  mongo_master:
    image: mongo
    container_name: mongo_master
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo_master:27017 --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - go-github
    restart: on-failure

  # mongo_slave_1:
  #   image: mongo
  #   container_name: mongo_slave_1
  #   links: 
  #     - mongo_master
  #   command: mongod --slave --source mongo_master
  #   networks:
  #     - go-github
  #   restart: on-failure
      
  # mongo_slave_2:
  #   image: mongo
  #   container_name: mongo_slave_2
    
  #   command: "--bind_ip_all --replSet rs0 --port 30002"
  #   networks:
  #     - go-github
  #   restart: on-failure

  go-github-fetcher:
    build: .
    restart: on-failure
    container_name: go-github-fetcher
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - MONGO_HOST=mongo_master
      - MONGO_PORT=27017
    networks:
      - go-github
    depends_on:
      mongo_master:
        condition: service_healthy


networks:
    go-github: