name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: cd ./go-github-api; go build -v ./...

    - name: Test
      run: cd ./go-github-api; go test -v ./...

  build-fetcher:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: cd ./go-github-fetcher; go build -v ./...

    - name: Test
      run: cd ./go-github-fetcher; go test -v ./...
